### ISSUE TITLE
Memory Leak when Importing Animation

### ISSUE THREAD

**Issue by 6yXJI0** [dtzxporter/SEATools#20]
Tested on Maya 2019 and 2020
[Video](https://puu.sh/FnpWz/aedd9ac6aa.mp4)

**Comment by dtzxporter** [comment]
This is not a memory leak per say, Maya has a setting to cache every single bone matrix, per frame, to speed up playback, you can turn this off, or limit the ram it can store with. Happens in newer mayas.
