### ISSUE TITLE
I cannot enable semodels, seanims plugin.

### ISSUE THREAD

**Issue by tquti123** [dtzxporter/SEATools#27]
![image](https://user-images.githubusercontent.com/116128662/235362670-b77139d6-f638-4d72-995e-ac6513fafb8e.png)
tried repeatedly, reinstalled multiple times and couldnt get it to turn on here is the line where the problem is
![image](https://user-images.githubusercontent.com/116128662/235362702-108f14d1-aa1f-4761-aa4a-fbc28f7dc569.png)
i am using maya 2023 which might be the problem

**Comment by dtzxporter** [comment]
You only enable SETools.py, not the other files.
